DoctorAppointmentSystem.WebUI/Controllers/AdminController.cs
using DoctorAppointmentSystem.Data.Abstract;
using DoctorAppointmentSystem.Entity;
using DoctorAppointmentSystem.WebUI.EmailServices;
using DoctorAppointmentSystem.WebUI.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Numerics;
using System.Security.AccessControl;

namespace DoctorAppointmentSystem.WebUI.Controllers
{
    public class AdminController : Controller
    {
        private IPatientDal _patientDal;
        private IAppointmentDal _appointmentDal;
        private IDoctorDal _doctorDal;
        private IScheduleDal _scheduleDal;
        private IDayOffDal _dayOffDal;
        private IEmailService _emailService;
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<AppRole> _roleManager;

        public AdminController(IPatientDal patientDal, IAppointmentDal appointmentDal, IDoctorDal doctorDal, IScheduleDal scheduleDal, UserManager<AppUser> userManager, RoleManager<AppRole> roleManager, IDayOffDal dayOffDal, IEmailService emailService)
        {
            _patientDal = patientDal;
            _appointmentDal = appointmentDal;
            _doctorDal = doctorDal;
            _scheduleDal = scheduleDal;
            _userManager = userManager;
            _roleManager = roleManager;
            _dayOffDal = dayOffDal;
            _emailService = emailService;
        }

        public IActionResult Index()
        {
            var model = new AdminDashboardViewModel()
            {
                doctors = _doctorDal.GetAll(),
                patients = _patientDal.GetAll(),
                appointments = _appointmentDal.GetAll(),
                monthlyAppointmentCounts = _appointmentDal.GetMonthlyAppointmentCounts(),
                monthlyPatientCounts = _patientDal.GetMonthlyPatientCounts(),
                yearlyAppointmentCount = new YearlyAppointmentCount
                {
                    ThisYear = _appointmentDal.GetAppointmentsCountThisYear(),
                    LastYear = _appointmentDal.GetAppointmentsCountLastYear()
                },
                yearlyPatientCount = new YearlyPatientCount
                {
                    ThisYear = _patientDal.GetPatientCountThisYear(),
                    LastYear = _patientDal.GetPatientCountLastYear()
                },
                dayOffs = _dayOffDal.GetAll().Where(i => i.StartDate > DateTime.Now).Count()

            };

            Console.WriteLine(model.yearlyAppointmentCount.LastYear);

            return View(model); 
        }

        public IActionResult DoctorList()
        {
            var doctors = _doctorDal.GetAll();

            return View(doctors);
        }

        [HttpGet]
        public IActionResult UpdateDoctor(int id)
        {
            if(id == 0) 
            {
                return NotFound();
            }

            var doctors = _doctorDal.GetById(id);

            return View(doctors);
        }

        [HttpPost]
        public IActionResult UpdateDoctor(Doctor model)
        {

            if (!ModelState.IsValid)
            {
                Console.WriteLine();
                return NotFound();
            }

            var doctor = _doctorDal.GetByUserEmail(model.Email);

            if (doctor == null)
            {
                return NotFound();
            }

            doctor.FullName = model.FullName;
            doctor.Bio = model.Bio;
            doctor.Email = doctor.Email;
            doctor.Picture = model.Picture;
            doctor.Specialization = model.Specialization;

            _doctorDal.Update(doctor);

            return RedirectToAction("DoctorList");
        }

        [HttpGet]
        public IActionResult CreateDoctor()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateDoctor(Doctor model)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }

            var doctor = new Doctor()
            {
                FullName = model.FullName,
                Bio = model.Bio,
                Email = model.Email,
                Picture = model.Picture,
                Specialization = model.Specialization,
            };

            AppUser user = new AppUser
            {
                FullName = model.FullName,
                UserName = model.Email,
                Email = model.Email,
            };
            
            _doctorDal.Create(doctor);
            await _userManager.CreateAsync(user, "123456");
            await _userManager.AddToRoleAsync(user, "Doctor");
            var doc = _doctorDal.GetByUserEmail(user.Email);
            if(doc == null) 
            {
                return NotFound();
            }

            List<Schedule> schedules = new List<Schedule>()
            {
                new Schedule {DayOfWeek = DayOfWeek.Monday, StartTime = new TimeSpan(9, 0, 0),EndTime = new TimeSpan(17, 0, 0),Interval = new TimeSpan(0, 30, 0), DoctorId = doc.DoctorId,IsWorkingDay = false},
                new Schedule {DayOfWeek = DayOfWeek.Tuesday, StartTime = new TimeSpan(9, 0, 0),EndTime = new TimeSpan(17, 0, 0),Interval = new TimeSpan(0, 30, 0), DoctorId = doc.DoctorId,IsWorkingDay = false},
                new Schedule {DayOfWeek = DayOfWeek.Wednesday, StartTime = new TimeSpan(9, 0, 0),EndTime = new TimeSpan(17, 0, 0),Interval = new TimeSpan(0, 30, 0), DoctorId = doc.DoctorId,IsWorkingDay = false},
                new Schedule {DayOfWeek = DayOfWeek.Thursday, StartTime = new TimeSpan(9, 0, 0),EndTime = new TimeSpan(17, 0, 0),Interval = new TimeSpan(0, 30, 0), DoctorId = doc.DoctorId,IsWorkingDay = false},
                new Schedule {DayOfWeek = DayOfWeek.Friday, StartTime = new TimeSpan(9, 0, 0),EndTime = new TimeSpan(17, 0, 0),Interval = new TimeSpan(0, 30, 0), DoctorId = doc.DoctorId,IsWorkingDay = false},
                new Schedule {DayOfWeek = DayOfWeek.Saturday, StartTime = new TimeSpan(9, 0, 0),EndTime = new TimeSpan(17, 0, 0),Interval = new TimeSpan(0, 30, 0), DoctorId = doc.DoctorId,IsWorkingDay = false},
            };
 
            foreach(var schedule in schedules)
            {
                _scheduleDal.Create(schedule);
            }


            return RedirectToAction("DoctorList");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteDoctor(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var doctor = _doctorDal.GetById(id);
            if (doctor == null)
            {
                return NotFound();
            }
            
            var user = await _userManager.FindByEmailAsync(doctor.Email);
            if (user == null)
            {
                return NotFound();
            }

            _scheduleDal.DeleteSchedulesById(doctor.DoctorId);
            _doctorDal.Delete(doctor);
            await _userManager.DeleteAsync(user);

            return RedirectToAction("DoctorList");
        }

        public IActionResult PatientList() 
        { 
            var patients = _patientDal.GetAll();

            return View(patients); 
        }

        public IActionResult CreatePatient()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePatient(Patient model)
        {
            if (ModelState.IsValid)
            {

                var patient = new Patient();

                patient.FullName = model.FullName;
                patient.Gender = model.Gender;
                patient.Email = model.Email;
                patient.Phone = model.Phone;
                patient.Age = model.Age;

                AppUser user = new AppUser
                {
                    FullName = model.FullName,
                    UserName = model.Email,
                    Email = model.Email,
                };

                _patientDal.Create(patient);
                await _userManager.CreateAsync(user, "123456");
                await _userManager.AddToRoleAsync(user, "Patient");
            }

            return RedirectToAction("PatientList");

        }

        [HttpGet]
        public IActionResult UpdatePatient(int id) 
        {
            if (id == 0)
            {
                return NotFound();
            }

            var patient = _patientDal.GetById(id);

            return View(patient);
        }

        [HttpPost]
        public IActionResult UpdatePatient(Patient model)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }

            var patient = _patientDal.GetByUserEmail(model.Email);

            if (patient == null)
            {
                return NotFound();
            }

            patient.FullName = model.FullName;
            patient.Gender = model.Gender;
            patient.Email = patient.Email;
            patient.Age = model.Age;
            patient.Phone = model.Phone;

            _patientDal.Update(patient);

            return RedirectToAction("PatientList");
        }

        [HttpPost]
        public async Task<IActionResult> DeletePatient(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var patient = _patientDal.GetById(id);
            if (patient == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByEmailAsync(patient.Email);
            if (user == null)
            {
                return NotFound();
            }

            _patientDal.Delete(patient);
            await _userManager.DeleteAsync(user);

            return RedirectToAction("PatientList");
        }

        public IActionResult LeaveRequests()
        {
            var days = _dayOffDal.GetAllByDoctor();

            return View(days);
        }

        [HttpPost]

DoctorAppointmentSystem.WebUI/Controllers/RoleController.cs
using DoctorAppointmentSystem.Data.Abstract;
using DoctorAppointmentSystem.Entity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DoctorAppointmentSystem.WebUI.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<AppRole> _roleManager; 
        private IPatientDal _patientDal;
        private IDoctorDal _doctorDal;
        private readonly UserManager<AppUser> _userManager;

        public RoleController(RoleManager<AppRole> roleManager, IPatientDal patientDal, IDoctorDal doctorDal, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _patientDal = patientDal;
            _doctorDal = doctorDal;
            _userManager = userManager;
        }

        public IActionResult RoleList()
        {
            var roles = _roleManager.Roles.ToList();

            return View(roles);
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(string newRole)
        {
            if(newRole == null) 
            {
                return NotFound();
            }

            await _roleManager.CreateAsync(new AppRole() { Name = newRole });

            return RedirectToAction("RoleList");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(int id)
        { 
            if(id == 0) 
            {
                return NotFound();
            }

             var role = await _roleManager.FindByIdAsync(id.ToString());

            if(role == null) 
            {
                return NotFound();
            }

            await _roleManager.DeleteAsync(role);

            return RedirectToAction("RoleList");
        }
    }
}

DoctorAppointmentSystem.WebUI/Views/Shared/_AdminLayout.cshtml
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Medisen</title>
    <link rel="stylesheet" href="/css/style.css">
    <link rel="shortcut icon" type="image/png" href="/images/logos/favicon.png" />
    <link rel="stylesheet" href="/css/styles.min.css" />
</head>

<body>
    <!--  Body Wrapper -->
    <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed">
        <!-- Sidebar Start -->
        <aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div>
                <div class="brand-logo d-flex align-items-center justify-content-between">
                    <a asp-controller="Admin" asp-action="Index" class="text-nowrap logo-img">
                        <img src="/images/logos/logo.png" width="180" alt="" />
                    </a>
                    <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                        <i class="ti ti-x fs-8"></i>
                    </div>
                </div>
                <!-- Sidebar navigation-->
                <partial name="_adminnavbar" />
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
        <!--  Sidebar End -->
        <!--  Main wrapper -->
        <div class="body-wrapper">
            <!--  Header Start -->
            <header class="app-header border-bottom">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <ul class="navbar-nav">
                        <li class="nav-item d-block d-xl-none">
                            <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                                <i class="ti ti-menu-2"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                                <i class="ti ti-bell-ringing"></i>
                                <div class="notification bg-primary rounded-circle"></div>
                            </a>
                        </li>
                    </ul>
                    <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
                        <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
                            <li class="nav-item">
                                <div class="d-flex align-items-center">
                                    <div class="me-3">
                                        <p class="mb-1">Today's Date</p>
                                        <p style="font-weight: bold;font-size: 14px; margin: 0;">@DateTime.Now.ToShortDateString()</p>
                                    </div>
                                    <div class="p-2" style="background-color: #e1e1e1;border-radius: 5px;">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-calendar-month"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 7a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-12z" /><path d="M16 3v4" /><path d="M8 3v4" /><path d="M4 11h16" /><path d="M7 14h.013" /><path d="M10.01 14h.005" /><path d="M13.01 14h.005" /><path d="M16.015 14h.005" /><path d="M13.015 17h.005" /><path d="M7.01 17h.005" /><path d="M10.01 17h.005" /></svg>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                                   aria-expanded="false">
                                    <img src="/images/profile/user-1.jpg" alt="" width="35" height="35" class="rounded-circle">
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                                    <div class="message-body">
                                        <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-user fs-6"></i>
                                            <p class="mb-0 fs-3">My Profile</p>
                                        </a>
                                        <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-mail fs-6"></i>
                                            <p class="mb-0 fs-3">My Account</p>
                                        </a>
                                        <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-list-check fs-6"></i>
                                            <p class="mb-0 fs-3">My Task</p>
                                        </a>
                                        <a asp-controller="Home" asp-action="Login" class="btn btn-outline-primary mx-3 mt-2 d-block">Logout</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <!--  Header End -->
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/js/sidebarmenu.js"></script>
    <script src="/js/app.min.js"></script>
    <script src="/lib/simplebar/dist/simplebar.js"></script>
    @* <script src="/js/dashboard.js"></script> *@
</body>

</html>

DoctorAppointmentSystem.WebUI/Views/Shared/_DoctorLayout.cshtml
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Medisen</title>
    <link rel="stylesheet" href="/css/style.css">
    <link rel="shortcut icon" type="image/png" href="/images/logos/favicon.png" />
    <link rel="stylesheet" href="/css/styles.min.css" />
</head>

<body>
    <!--  Body Wrapper -->
    <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed">
        <!-- Sidebar Start -->
        <aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div>
                <div class="brand-logo d-flex align-items-center justify-content-between">
                    <a asp-controller="Doctor" asp-action="Index" class="text-nowrap logo-img">
                        <img src="/images/logos/logo.png" width="180" alt="" />
                    </a>
                    <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                        <i class="ti ti-x fs-8"></i>
                    </div>
                </div>
                <!-- Sidebar navigation-->
                <partial name="_doctornavbar" />
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
        <!--  Sidebar End -->
        <!--  Main wrapper -->
        <div class="body-wrapper">
            <!--  Header Start -->
            <header class="app-header border-bottom">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <ul class="navbar-nav">
                        <li class="nav-item d-block d-xl-none">
                            <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                                <i class="ti ti-menu-2"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                                <i class="ti ti-bell-ringing"></i>
                                <div class="notification bg-primary rounded-circle"></div>
                            </a>
                        </li>
                    </ul>
                    <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
                        <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
                            <li class="nav-item">
                                <div class="d-flex align-items-center">
                                    <div class="me-3">
                                        <p class="mb-1">Today's Date</p>
                                        <p style="font-weight: bold;font-size: 14px; margin: 0;">@DateTime.Now.ToShortDateString()</p>
                                    </div>
                                    <div class="p-2" style="background-color: #e1e1e1;border-radius: 5px;">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-calendar-month"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 7a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-12z" /><path d="M16 3v4" /><path d="M8 3v4" /><path d="M4 11h16" /><path d="M7 14h.013" /><path d="M10.01 14h.005" /><path d="M13.01 14h.005" /><path d="M16.015 14h.005" /><path d="M13.015 17h.005" /><path d="M7.01 17h.005" /><path d="M10.01 17h.005" /></svg>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                                   aria-expanded="false">
                                    <img src="/images/profile/user-1.jpg" alt="" width="35" height="35" class="rounded-circle">
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                                    <div class="message-body">
                                        <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-user fs-6"></i>
                                            <p class="mb-0 fs-3">My Profile</p>
                                        </a>
                                        <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-mail fs-6"></i>
                                            <p class="mb-0 fs-3">My Account</p>
                                        </a>
                                        <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-list-check fs-6"></i>
                                            <p class="mb-0 fs-3">My Task</p>
                                        </a>
                                        <a asp-controller="Home" asp-action="Logout" class="btn btn-outline-primary mx-3 mt-2 d-block">Logout</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <!--  Header End -->
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/js/sidebarmenu.js"></script>
    <script src="/js/app.min.js"></script>
    <script src="/lib/simplebar/dist/simplebar.js"></script>
</body>

</html>

DoctorAppointmentSystem.WebUI/Views/Shared/_adminnavbar.cshtml
<nav class="sidebar-nav scroll-sidebar" data-simplebar="">
    <ul id="sidebarnav">
        <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">Pages</span>
        </li>
        <li class="sidebar-item">
            <a asp-controller="Admin" asp-action="Index" class="sidebar-link" aria-expanded="false">
                <span>
                    <i class="ti ti-home"></i>
                </span>
                <span class="hide-menu">Dashboard</span>
            </a>
        </li>
        <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">Users</span>
        </li>
        <li class="sidebar-item">
            <a class="sidebar-link" data-bs-toggle="collapse" href="#doctormanager" aria-expanded="false" aria-controls="tables">
                <span>
                    <i class="ti ti-users"></i>
                </span>
                <span class="menu-title">Doctor Manager</span>
                <i class="ti ti-chevron-right"></i>
            </a>
            <div class="collapse" id="doctormanager">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a asp-controller="Admin" asp-action="DoctorList" class="nav-link">Doctor List</a></li>
                </ul>
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a asp-controller="Admin" asp-action="CreateDoctor" class="nav-link">Create Doctor</a></li>
                </ul>
            </div>
        </li>
        <li class="sidebar-item">
            <a class="sidebar-link" data-bs-toggle="collapse" href="#patientmanager" aria-expanded="false" aria-controls="tables">
                <span>
                    <i class="ti ti-users"></i>
                </span>
                <span class="menu-title">Patient Manager</span>
                <i class="ti ti-chevron-right"></i>
            </a>
            <div class="collapse" id="patientmanager">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a asp-controller="Admin" asp-action="PatientList" class="nav-link">Patient List</a></li>
                </ul>
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a asp-controller="Admin" asp-action="CreatePatient" class="nav-link">Create Patient</a></li>
                </ul>
            </div>
        </li>
        <li class="sidebar-item">
            <a class="sidebar-link" data-bs-toggle="collapse" href="#authorizations" aria-expanded="false" aria-controls="tables">
                <span>
                    <i class="ti ti-checkup-list"></i>
                </span>
                <span class="menu-title">Authorizations</span>
                <i class="ti ti-chevron-right"></i>
            </a>
            <div class="collapse" id="authorizations">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a asp-controller="Role" asp-action="RoleList" class="nav-link">Roles</a></li>
                </ul>
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a asp-controller="Role" asp-action="PatientList" class="nav-link">Patient Roles</a></li>
                </ul>
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a asp-controller="Role" asp-action="CreatePatient" class="nav-link">Doctor Roles</a></li>
                </ul>
            </div>
        </li>
        <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">Requests</span>
        </li>
        <li class="sidebar-item">
            <a asp-controller="Admin" asp-action="LeaveRequests" class="sidebar-link" aria-expanded="false">
                <span>
                    <i class="ti ti-calendar-question"></i>
                </span>
                <span class="hide-menu">Leave Requests</span>
            </a>
        </li>
        <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">Log Out</span>
        </li>
        <li class="sidebar-item">
            <a asp-controller="Login" asp-action="Logout" class="sidebar-link alert alert-secondary" aria-expanded="false">
                <span>
                    <i class="ti ti-logout"></i>
                </span>
                <span class="hide-menu">Log out</span>
            </a>
        </li>
    </ul>
</nav>

<style>
    .left-sidebar .sidebar-nav .sidebar-item .sidebar-link[aria-expanded="true"] i.ti-chevron-right:before {
        -moz-transform: rotate(90deg);
        -o-transform: rotate(90deg);
        -ms-transform: rotate(90deg);
        -webkit-transform: rotate(90deg);
        transform: rotate(90deg);
    }

    .left-sidebar .sidebar-nav .sidebar-item .sidebar-link i.ti-chevron-right:before {
        display: inline-block;
        position: absolute;
        top: 12px;
        right: 20px;
        -webkit-transition: all 0.2s ease-in;
        -moz-transition: all 0.2s ease-in;
        -ms-transition: all 0.2s ease-in;
        -o-transition: all 0.2s ease-in;
        transition: all 0.2s ease-in;
    }

    .left-sidebar .nav.sub-menu {
        margin-bottom: 0;
        margin-top: 0;
        list-style: none;
        padding: 0.25rem 0 0 3.07rem;
        padding-bottom: 12px;
    }

        .left-sidebar .nav.sub-menu .nav-item {
            padding: 0;
        }

            .left-sidebar .nav.sub-menu .nav-item::before {
                content: '';
                width: 5px;
                height: 5px;
                position: absolute;
                margin-top: 16px;
                border-radius: 50%;
                background: #b2b2b2;
            }

            .left-sidebar .nav.sub-menu .nav-item .nav-link {
                color: black;
                padding: 0.7rem 1rem;
                position: relative;
                font-size: 0.875rem;
                line-height: 1;
                height: auto;
                border-top: 0;
            }

                .left-sidebar .nav.sub-menu .nav-item .nav-link:hover {
                    color: #5D87FF;
                }

                .left-sidebar .nav.sub-menu .nav-item .nav-link.active {
                    color: #5D87FF;
                    background: transparent;
                }

            .left-sidebar .nav.sub-menu .nav-item:hover {
                background: transparent;
            }

</style>