DoctorAppointmentSystem.WebUI/Controllers/PatientAccountController.cs
using DoctorAppointmentSystem.Data.Abstract;
using DoctorAppointmentSystem.Entity;
using DoctorAppointmentSystem.WebUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DoctorAppointmentSystem.WebUI.Controllers
{
    [Authorize(Roles = "Patient")]
    public class PatientAccountController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private IPatientDal _patientDal;

        public PatientAccountController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, IPatientDal patientDal)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _patientDal = patientDal;
        }

        [HttpGet]
        public IActionResult AccountSettings()
        {
            string? UserName = _userManager.GetUserName(User);
            if (UserName == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var patient = _patientDal.GetByUserEmail(UserName);

            if (patient == null)
            {
                return NotFound();
            }

            var model = new Patient() 
            { 
                FullName=patient.FullName,
                Age=patient.Age,
                Gender=patient.Gender,
                Email=patient.Email,
                Phone=patient.Phone,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AccountSettings(Patient model)
        {
            if (ModelState.IsValid) 
            {
                string? UserEmail = _userManager.GetUserName(User);
                if (UserEmail == null)
                {
                    return RedirectToAction("Index", "Login");
                }

                var patient = _patientDal.GetByUserEmail(UserEmail);

                if (patient == null) 
                {
                    return NotFound();
                }

                var user = await _userManager.GetUserAsync(User);

                if(user == null) 
                {
                    return NotFound();
                }

                patient.FullName = model.FullName;
                patient.Gender = model.Gender;
                patient.Email = model.Email;
                patient.Phone = model.Phone;
                patient.Age = model.Age;

                _patientDal.Update(patient);
                await _userManager.SetEmailAsync(user, model.Email);
                await _userManager.SetUserNameAsync(user, model.Email);
                await _signInManager.RefreshSignInAsync(user);

                
            }

            return RedirectToAction("Index","Patient");
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(string? OldPassword, string? NewPassword)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound();
            }

            if ((OldPassword != null) && (NewPassword != null))
            {
                var changePasswordResult = await _userManager.ChangePasswordAsync(user, OldPassword, NewPassword);
                if (!changePasswordResult.Succeeded)
                {
                    foreach (var error in changePasswordResult.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                        await Console.Out.WriteLineAsync(error.ToString());
                    }
                    return RedirectToAction("AccountSettings");
                }
            }

            await _signInManager.RefreshSignInAsync(user);
            return RedirectToAction("Index","Patient");
        }

        public IActionResult Details() 
        {
            string? UserName = _userManager.GetUserName(User);
            if (UserName == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var patient = _patientDal.GetByUserEmail(UserName);

            if (patient == null)
            {
                return NotFound();
            }

            var model = new Patient()
            {
                FullName = patient.FullName,
                Age = patient.Age,
                Gender = patient.Gender,
                Email = patient.Email,
                Phone = patient.Phone,
            };

            return View(model);
        }

        public async Task<IActionResult> Delete()
        {
            var user = await _userManager.GetUserAsync(User);
            string? UserName = _userManager.GetUserName(User);
            if (UserName == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var patient = _patientDal.GetByUserEmail(UserName);
            if (patient == null) 
            {
                return NotFound();
            }

            _patientDal.Delete(patient);
            await _userManager.DeleteAsync(user);


            return RedirectToAction("Logout","Login");
        }
    }
}

DoctorAppointmentSystem.WebUI/Controllers/PatientController.cs
using DoctorAppointmentSystem.WebUI.Models;
using DoctorAppointmentSystem.Entity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using DoctorAppointmentSystem.Data.Abstract;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using DoctorAppointmentSystem.WebUI.EmailServices;
using Microsoft.AspNetCore.Identity.UI.Services;

namespace DoctorAppointmentSystem.WebUI.Controllers
{
    [Authorize(Roles = "Patient")]
    public class PatientController : Controller
    {
        private readonly ILogger<PatientController> _logger;
        private IPatientDal _patientDal;
        private IAppointmentDal _appointmentDal;
        private IDoctorDal _doctorDal;
        private IScheduleDal _scheduleDal;
        private IDayOffDal _dayOffDal;
        private readonly UserManager<AppUser> _userManager;
        private readonly IEmailService _emailSender;


        public PatientController(ILogger<PatientController> logger, IPatientDal patientDal, IAppointmentDal appointmentDal, IDoctorDal doctorDal, IScheduleDal scheduleDal, UserManager<AppUser> userManager, IEmailService emailSender, IDayOffDal dayOffDal)
        {
            _logger = logger;
            _patientDal = patientDal;
            _appointmentDal = appointmentDal;
            _doctorDal = doctorDal;
            _scheduleDal = scheduleDal;
            _userManager = userManager;
            _emailSender = emailSender;
            _dayOffDal = dayOffDal;
        }

        public IActionResult Index()
        {
            
            string? UserEmail = _userManager.GetUserName(User);
            if(UserEmail == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var patient = _patientDal.GetByUserEmail(UserEmail);

            if (patient == null)
            {
                return NotFound();
            }

            patient.Appointments = _appointmentDal.GetAppointmentsWithPatientId(patient.PatientId)
                .OrderByDescending(appointment => appointment.DateTime)
                .Take(5)
                .ToList(); 

            return View(patient);
        }

        public IActionResult DoctorsList()
        {
            List<Doctor> doctor = new List<Doctor>();
            doctor = _doctorDal.GetAll();
            
            return View(doctor);
        }

        public IActionResult Details(int id) 
        {
            Doctor doctor = new Doctor();
            doctor = _doctorDal.GetDoctorWithSchedule(id);

            return View(doctor);
        }

        public IActionResult Appointment(int id)
        {
            if (id == 0)
            {
                return RedirectToAction("DoctorList");
            }

            string? UserName = _userManager.GetUserName(User);

             
            if (UserName == null)
            {
                return RedirectToAction("Index", "Login");
            }

            PatientAppointmentViewModel model = new PatientAppointmentViewModel();
            model.Patient = _patientDal.GetByUserEmail(UserName);
            model.Doctor = _doctorDal.GetById(id);
            model.Doctor.Appointments = _appointmentDal.GetAppointmentsWithDoctorId(id);
            model.Doctor.Schedules = _scheduleDal.GetSchedulesByDoctorId(id);
            model.daysOff = _dayOffDal.GetDaysByDoctorId(id);
           
            return View(model);
        }
        
        [HttpPost]
        public IActionResult Appointment(int patientId, int doctorId, string date)
        {
            var patient = _patientDal.GetById(patientId);
            var doctor = _doctorDal.GetById(doctorId);

            Appointment appointment = new Appointment();

            appointment.DateTime = DateTime.Parse(date);
            appointment.PatientId = patientId;
            appointment.DoctorId = doctorId;
            appointment.IsApproved = State.Waiting;
            appointment.Note = " ";
            appointment.CreatedDate = DateTime.Now;

            _emailSender.Execute("anilalkis86@gmail.com", "Appointment Information", $"Dear {patient.FullName},\n\nYour appointment request has been received. Detailed information is added below.\n\n Appointment Date: {appointment.DateTime.ToShortTimeString()} \n\n Appointment Time: {appointment.DateTime.ToLongDateString()}\n\nDoctor Name: {doctor.FullName}\n\nAppointment Status: Waiting\n\nWe wish you a good day.\n\nMedisen");
            _appointmentDal.Create(appointment);

            return RedirectToAction("Index");
        }

        public IActionResult MyAppointments()
        {
            string? UserName = _userManager.GetUserName(User);

            if (UserName == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var patient = _patientDal.GetByUserEmail(UserName);
            patient.Appointments = _appointmentDal.GetAppointmentsWithPatientId(patient.PatientId);

            return View(patient);
        }

        [HttpPost]
        public IActionResult MyAppointments(int appointmentId)
        {
            Appointment appointment = _appointmentDal.GetAppointmentById(appointmentId);
            _appointmentDal.Delete(appointment);

            return RedirectToAction("Index");
        }

        public IActionResult Settings() 
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }
}

DoctorAppointmentSystem.WebUI/Views/Patient/Appointment.cshtml
@model PatientAppointmentViewModel
@{
    List<DayOfWeek> scheduleDays = new List<DayOfWeek>();
    foreach (var schedule in Model.Doctor.Schedules)
    {
        if(schedule.IsWorkingDay)
        {
            scheduleDays.Add(schedule.DayOfWeek);
        }
    }
    List<DateTime> appointmentDays = new List<DateTime>();
    foreach (var appointment in Model.Doctor.Appointments)
    {
        appointmentDays.Add(appointment.DateTime);
    }
    List<DateTime> offDays = new List<DateTime>();
    foreach (var dayoff in Model.daysOff)
    {
        if(dayoff.IsApproved != State.Approved)
        {
            DateTime current = dayoff.StartDate;
            while (current <= dayoff.EndDate)
            {
                offDays.Add(current);
                current = current.AddDays(1);
            }
        }
    }


    DateTime day = DateTime.Today.AddDays(1);
    DateTime endDate = day.AddDays(14);

    TimeSpan startTime = @Model.Doctor.Schedules[0].StartTime;
    TimeSpan endTime = @Model.Doctor.Schedules[0].EndTime;
    TimeSpan slotDuration = @Model.Doctor.Schedules[0].Interval;

    //Launch

    TimeSpan LStart = new TimeSpan(12, 0, 0);
    TimeSpan LEnd = new TimeSpan(13, 0, 0);

    int counter = 1;

    for (DateTime date = day; date <= endDate; date = date.AddDays(1))
    {
        if(scheduleDays.Contains(date.DayOfWeek) && !(offDays.Contains(date)))
        {
            <div class="card mt-3 p-0">
                <div class="card-header d-flex align-items-center justify-content-center" data-bs-toggle="collapse" href="#Collapse@(counter.ToString())" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">
                    <span>
                        @date.ToShortDateString() - @date.DayOfWeek.ToString()
                    </span>    
                    <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-caret-down"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M6 10l6 6l6 -6h-12" /></svg>
                </div>
                <div class="collapse multi-collapse p-2" id="Collapse@(counter.ToString())">
                    @for (TimeSpan currentTime = startTime; currentTime <= endTime; currentTime = currentTime.Add(slotDuration))
                    {
                        if (!(currentTime >= LStart && currentTime <= LEnd) && !(appointmentDays.Contains(date.AddHours(currentTime.TotalHours))))
                        {
                            <button value="@date.ToShortDateString()" onclick="setdate(this)" type="button" class="set btn btn-primary m-1" data-toggle="modal" data-target="#exampleModalCenter">@currentTime.ToString("hh\\:mm")</button>

                        }
                        else if (!(currentTime >= LStart && currentTime <= LEnd))
                        {
                            <button type="button" class="btn btn-outline-primary m-1" disabled>@currentTime.ToString("hh\\:mm")</button>

                        }
                    }
                </div>
            </div>
            counter++;
        }   
    }
}

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Do you want to create the appointment?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
                <form method="post" asp-controller="Patient" asp-action="Appointment">
            <div class="modal-body">
                    <input type="hidden" class="form-control" placeholder="Patient Name" name="patientId" value="@Model.Patient.PatientId">
                    <input type="hidden" class="form-control" placeholder="Patient Name" name="doctorId" value="@Model.Doctor.DoctorId">
                    <input id="date" type="hidden" class="form-control" placeholder="Patient Name" name="date">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Make An Appointment</button>
            </div>
            <div class="modal-footer">
                
            </div>
                </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script>
    function setdate(button) {
        document.getElementById("date").value = button.value+ " " + button.innerHTML;
    }
</script>

DoctorAppointmentSystem.WebUI/Views/Patient/Details.cshtml
@model Doctor

<div class="my-1 mx-1 mb-5">
    <div class="d-flex justify-content-between align-items-center">
        <h3>Detail</h3>
        <div class="d-flex align-items-center">
            <div class="me-3">
                <p class="mb-1">Today's Date</p>
                <p style="font-weight: bold;font-size: 18px; margin: 0;">26/03/2024</p>
            </div>
            <div class="p-2" style="background-color: #e1e1e1;border-radius: 5px;">
                <span class="material-symbols-outlined" style="font-size: 35px;">
                    calendar_month
                </span>
            </div>
        </div>
    </div>
</div>
<div class="d-flex mx-1 justify-content-center">
    <div class="card mb-3" style="max-width: 100%;">
        <div class="row g-0">
            <div class="col-md-4">
                <!-- <img src="..." class="img-fluid rounded-start" alt="..."> -->
                <span class="material-symbols-outlined" style="font-size: 150px;">
                    person
                </span>
            </div>
            <div class="col-md-8">
                <div class="card-body border-start">
                    <h5 class="card-title">@Model.FullName</h5>
                    <p class="card-text">@Model.Specialization</p>
                    <p class="card-text">@Model.Bio</p>
                    <p class="card-text"><ins>Working Days:</ins></p>
                    @foreach(var schedule in Model.Schedules)
                    {
                        <p class="card-text"><em>@schedule.DayOfWeek.ToString()</em></p>
                        <p class="card-text"><em>@schedule.StartTime.ToString() - @schedule.EndTime.ToString()</em></p>
                    }

                    
                </div>
            </div>
        </div>
    </div>
</div>

DoctorAppointmentSystem.WebUI/Views/Patient/DoctorsList.cshtml
@model List<Doctor>

@foreach(var doctor in Model)
{
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-3">
                <img src="/images/doctors/@doctor.Picture" class="img-thumbnail rounded-start">
            </div>
            <div class="col-md-9">
                <div class="card-body position-relative h-100">
                    <h5 class="card-title">@doctor.FullName</h5>
                    <p class="card-text"><small class="text-body-secondary">@doctor.Specialization</small></p>
                    <p class="card-text">@doctor.Bio</p>
                    <div class="position-absolute" style="bottom: 10px; right: 10px;">
                        <a asp-controller="Patient" asp-action="Details" asp-route-id="@doctor.DoctorId" class="btn btn-primary m-1">Details</a>
                        <a asp-controller="Patient" asp-action="Appointment" asp-route-id="@doctor.DoctorId" class="btn btn-primary m-1">Make an Appointment</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

DoctorAppointmentSystem.WebUI/Views/Patient/Index.cshtml
@model Patient

<div style="background-color:var(--bs-info-bg-subtle)" class="card">
    <div class="card-body">
        <h5 class="mb-3">Welcome!</h5>
        <h3 class="mb-3">@Model.FullName</h3>
        <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere mollitia fuga iste praesentium alias optio, sapiente minus magni quos doloremque laboriosam voluptatem molestiae dicta commodi aspernatur quo dolorum saepe at!</p>
        <form class="form-inline home-searchbar d-flex w-50">
            <input style="background-color: white;" class="form-control mr-sm-2 me-2" type="search" placeholder="Search Doctor" aria-label="Search">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-lg-4 d-flex align-items-stretch">
        <div class="card w-100">
            <div class="card-body p-4">
                <div class="mb-4">
                    <h5 class="card-title fw-semibold">Past Bookings</h5>
                </div>
                <ul class="timeline-widget mb-0 position-relative mb-n5">
                    @foreach (var appointment in Model.Appointments)
                    {
                        if(appointment.DateTime < DateTime.Now)
                        {
                            <li class="timeline-item d-flex position-relative overflow-hidden">
                                <div class="timeline-time text-dark flex-shrink-0 text-end ">
                                    <span style="display:block" class="fw-semibold">
                                        @appointment.DateTime.ToShortDateString()
                                    </span>
                                    <span>
                                        @appointment.DateTime.ToShortTimeString()
                                    </span>
                                </div>

                                <div class="timeline-badge-wrap d-flex flex-column align-items-center">
                                    <span class="timeline-badge border-2 border border-primary flex-shrink-0 my-8"></span>
                                    <span class="timeline-badge-border d-block flex-shrink-0"></span>
                                </div>
                                <div class="timeline-desc fs-3 text-dark mt-n1 fw-semibold">@appointment.Doctor.FullName</div>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>

    @* Upcoming Bookings *@
    <div class="col-lg-8 d-flex align-items-stretch">
        <div class="card w-100">
            <div class="card-body p-4">
                <h5 class="card-title fw-semibold mb-4">Your Upcoming Bookings</h5>
                <div class="table-responsive">
                    <table class="table text-nowrap mb-0 align-middle table-hover table-striped">
                        <thead class="text-dark fs-4">
                            <tr>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Id</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Doctor</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Scheduled Date & Time</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Approval Status</h6>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var appointment in Model.Appointments)
                            {
                                if(appointment.DateTime > DateTime.Now)
                                {
                                    <tr>
                                    <td class="border-bottom-0"><h6 class="fw-semibold mb-0">@appointment.AppointmentId</h6></td>
                                    <td class="border-bottom-0">
                                        <h6 class="fw-semibold mb-1">@appointment.Doctor.FullName</h6>
                                    </td>
                                    <td class="border-bottom-0">
                                        <p class="mb-0 fw-normal">@appointment.DateTime.ToLongDateString()</p>
                                    </td>
                                    <td class="border-bottom-0">
                                            @if (appointment.IsApproved == State.Approved)
                                            {
                                                <span class="badge bg-success rounded-3 fw-semibold">Approved</span>
                                            }
                                            else if (appointment.IsApproved == State.NotApproved)
                                            {
                                                <span class="badge bg-danger rounded-3 fw-semibold">Not Approved</span>
                                            }
                                            else if (appointment.IsApproved == State.Waiting)
                                            {
                                                <span class="badge bg-warning rounded-3 fw-semibold">Waiting</span>
                                            }
                                    </td>
                                </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

DoctorAppointmentSystem.WebUI/Views/Patient/MyAppointments.cshtml
@model Patient

@{
    Layout = "_PatientLayout";
}



@foreach(var appointment in @Model.Appointments)
{
    if (appointment.DateTime > DateTime.Now)
    {
        <div class="card alert alert-secondary">
            <div class="card-header fw-bold d-flex justify-content-between">
                <span>
                    @appointment.DateTime.ToShortDateString() - @appointment.DateTime.DayOfWeek.ToString()
                </span>
                <span>
                    @if (appointment.IsApproved == State.Approved)
                    {
                        <span class="badge bg-success rounded-3 fw-semibold">Approved</span>
                    }
                    else if (appointment.IsApproved == State.NotApproved)
                    {
                        <span class="badge bg-danger rounded-3 fw-semibold">Not Approved</span>
                    }
                    else if (appointment.IsApproved == State.Waiting)
                    {
                        <span class="badge bg-warning rounded-3 fw-semibold">Waiting</span>
                    }
                </span>
            </div>
            <div class="card-body">
                <p class="mb-0">Booking Date: ###</p>
                <h4 class="card-title fw-semibold my-4">@appointment.Doctor.FullName</h4>
                <p class="mb-0"><small>Sheduled Date: @appointment.DateTime.ToShortDateString()</small></p>
                <p class="mb-0"><small>Sheduled Time:</small> <b>@appointment.DateTime.ToShortTimeString()</b></p>
                <form asp-controller="Patient" asp-action="MyAppointments" method="post">
                    <input type="hidden" name="appointmentId" value="@appointment.AppointmentId" />
                    <button type="submit" class="btn btn-danger w-100 my-2">Cancel Booking</button>
                </form>
            </div>
        </div>
    }
}

DoctorAppointmentSystem.WebUI/Views/Patient/Settings.cshtml
@{
    Layout = "_PatientLayout";
}

<div class="card">
    <a asp-controller="PatientAccount" asp-action="AccountSettings" class="card-body d-flex align-items-center">
        <i class="ti ti-home-cog settings "></i>
        <h1 class="card-title fw-semibold ">Account Settings</h1>
    </a>
</div>
<div class="card">
    <a asp-controller="PatientAccount" asp-action="Details" class="card-body d-flex align-items-center">
        <i class="ti ti-eye settings "></i>
        <h1 class="card-title fw-semibold ">View Account Details</h1>
    </a>
</div>
<div class="card">
    <button style="background:transparent;border:none" class="card-body d-flex align-items-center" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <i class="ti ti-circle-minus danger settings"></i>
        <h1 style="color:red" class="card-title fw-semibold ">Delete Acoount</h1>
    </button>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fw-bold" id="exampleModalLabel">Are you sure you want to delete the account?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex justify-content-center">
                <a asp-controller="PatientAccount" asp-action="Delete" class="btn btn-danger">Delete Account</a>
            </div>
        </div>
    </div>
</div>

<style>
    .settings {
        padding: 15px;
        font-size: 40px;
        color: #5D87FF;
        background: whitesmoke;
        margin-right: 15px;
    }
</style>