DoctorAppointmentSystem.WebUI/Controllers/DoctorController.cs
using DoctorAppointmentSystem.Data.Abstract;
using DoctorAppointmentSystem.Entity;
using DoctorAppointmentSystem.WebUI.EmailServices;
using DoctorAppointmentSystem.WebUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using System.Numerics;

namespace DoctorAppointmentSystem.WebUI.Controllers
{
    [Authorize(Roles = "Doctor,Admin")]
    public class DoctorController : Controller
    {
        private IPatientDal _patientDal;
        private IAppointmentDal _appointmentDal;
        private IDoctorDal _doctorDal;
        private IScheduleDal _scheduleDal;
        private IDayOffDal _dayOffDal;
        private IEmailService _emailService;
        private readonly UserManager<AppUser> _userManager;


        public DoctorController(IPatientDal patientDal, IAppointmentDal appointmentDal, IDoctorDal doctorDal, IScheduleDal scheduleDal, UserManager<AppUser> userManager, IDayOffDal dayOffDal, IEmailService emailService)
        {
            _patientDal = patientDal;
            _appointmentDal = appointmentDal;
            _doctorDal = doctorDal;
            _scheduleDal = scheduleDal;
            _userManager = userManager;
            _dayOffDal = dayOffDal;
            _emailService = emailService;

        }
        public IActionResult Index()
        {
            string? UserEmail = _userManager.GetUserName(User);

            if (UserEmail == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var doctor = _doctorDal.GetByUserEmail(UserEmail);
            doctor.Appointments = _appointmentDal.GetAppointmentsWithDoctorId(doctor.DoctorId);
            
            return View(doctor);
        }

        public IActionResult AppointmentList() 
        {
            string? UserEmail = _userManager.GetUserName(User);

            if (UserEmail == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var doctor = _doctorDal.GetByUserEmail(UserEmail);
            doctor.Appointments = _appointmentDal.GetAppointmentsWithDoctorId(doctor.DoctorId)
                .Where(x => x.DateTime >= DateTime.Now).ToList();

            return View(doctor.Appointments);
        }
        public IActionResult PastAppointmentList()
        {
            string? UserEmail = _userManager.GetUserName(User);

            if (UserEmail == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var doctor = _doctorDal.GetByUserEmail(UserEmail);
            doctor.Appointments = _appointmentDal.GetAppointmentsWithDoctorId(doctor.DoctorId)
                .Where(x => x.DateTime < DateTime.Now).ToList();

            return View(doctor.Appointments);
        }

        public IActionResult Schedule()
        {
            string? UserEmail = _userManager.GetUserName(User);

            if (UserEmail == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var doctor = _doctorDal.GetByUserEmail(UserEmail);
            List<Schedule> schedules = new List<Schedule>();
            schedules = _scheduleDal.GetSchedulesByDoctorId(doctor.DoctorId);

            return View(schedules);
        }

        [HttpPost]
        public IActionResult Schedule(List<Schedule> schedules)
        {
            if(schedules == null)
            {
                return NotFound();
            }

            string? UserEmail = _userManager.GetUserName(User);

            if (UserEmail == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var doctorid = _doctorDal.GetByUserEmail(UserEmail).DoctorId;

            foreach(var item in schedules)
            {
                _scheduleDal.Update(item);
            }

            var newSchedule = _scheduleDal.GetSchedulesByDoctorId(doctorid);

            return View(newSchedule);
        }

        public IActionResult LeaveRequest()
        { 
            return View(); 
        }

        [HttpPost]
        public IActionResult LeaveRequest(DayOff dayOff)
        {
            if(dayOff == null)
            {
                return NotFound();
            }

            string? UserEmail = _userManager.GetUserName(User);

            if (UserEmail == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var doctorid = _doctorDal.GetByUserEmail(UserEmail).DoctorId;
            dayOff.DoctorId = doctorid;
            dayOff.IsApproved = State.Waiting;
            _dayOffDal.Create(dayOff);

            return RedirectToAction("OffDays");
        }

        public IActionResult OffDays()
        {
            string? UserEmail = _userManager.GetUserName(User);

            if (UserEmail == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var doctorid = _doctorDal.GetByUserEmail(UserEmail).DoctorId;
            var days =  _dayOffDal.GetDaysByDoctorId(doctorid);

            return View(days); 
        }
        
        [HttpPost]
        public IActionResult OffDays(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            string? UserEmail = _userManager.GetUserName(User);

            if (UserEmail == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var doctorid = _doctorDal.GetByUserEmail(UserEmail).DoctorId;
            var day = _dayOffDal.GetById(id);
            _dayOffDal.Delete(day);

            var days = _dayOffDal.GetDaysByDoctorId(doctorid);

            return View(days);
        }

        [HttpPost]
        public IActionResult UpdateStatus(int AppointmentId, State isApproved)
        {
            var appointment = _appointmentDal.GetAppointmentById(AppointmentId);

            if(appointment == null)
            {
                return NotFound();
            }
            
            if(isApproved == State.Approved)
            {
                appointment.IsApproved = State.Approved;
                TempData["ConfirmMessage"] = "appointment confirmed.";
                _emailService.Execute("anilalkis86@gmail.com", "Appointment Confirmed",$"Dear {appointment.Patient.FullName},\n\nYour appointment has been confirmed. Detailed information is added below.\n\nAppointment Date: {appointment.DateTime.ToShortTimeString()}\n\nAppointment Time: {appointment.DateTime.ToLongDateString()}\n\nDoctor Name: {appointment.Doctor.FullName}\n \nAppointment Status: {appointment.IsApproved.ToString()}\n\nWe wish you a good day.\n\nMedisen");
            }
            else
            {
                appointment.IsApproved = State.NotApproved;
                TempData["CancelMessage"] = "appointment has been cancelled.";
                _emailService.Execute("anilalkis86@gmail.com", "Appointment Confirmed", $"Dear {appointment.Patient.FullName},\n\nYour appointment could not be confirmed. Detailed information is added below.\n\nAppointment Date: {appointment.DateTime.ToShortTimeString()}\n\nAppointment Time: {appointment.DateTime.ToLongDateString()}\n\nDoctor Name: {appointment.Doctor.FullName}\n \nAppointment Status: {appointment.IsApproved.ToString()}\n\nWe wish you a good day.\n\nMedisen");
            }
            _appointmentDal.Update(appointment);
            return RedirectToAction("AppointmentList");
        }

        public IActionResult PatientProfile(int id) 
        {
            if (id == 0)
            {
                return NotFound();
            }
            var patient = _patientDal.GetById(id);
            patient.Appointments = _appointmentDal.GetAppointmentsWithPatientId(id);

            return View(patient);
        }

        [HttpGet]
        public IActionResult AppointmentDetails(int id)
        {
            if(id == 0) 
            {
                return NotFound();
            }
            var app = _appointmentDal.GetAppointmentById(id);

            return View(app);
        }

        [HttpPost]
        public IActionResult AppointmentDetails(string note,int id)
        {
            if(id==0)
            {
                return NotFound();
            }

            var app = _appointmentDal.GetAppointmentById(id);
            var newapp = new Appointment()
            {
                AppointmentId = app.AppointmentId,
                DateTime = app.DateTime,
                IsApproved = app.IsApproved,
                PatientId = app.PatientId,
                DoctorId = app.DoctorId,
                Note = note,
            };
            _appointmentDal.Update(newapp);
            newapp = _appointmentDal.GetAppointmentById(id);
            return View(newapp);
        }
    }
}

DoctorAppointmentSystem.WebUI/Views/Doctor/AppointmentDetails.cshtml
@model Appointment
@{
    Layout = "_DoctorLayout";
}

<div class="card">
    <div class="card-body">
        <h1 style="font-size:28px" class="card-title fw-semibold mb-4">Appointment Details</h1>
        <p class="mb-1"><b>Date:</b>@Model.DateTime.ToString()</p>
        <p class="mb-1"><b>Doctor:</b>@Model.Doctor.FullName</p>
        @if (Model.IsApproved == State.Approved)
        {
            <span class="badge bg-success rounded-3 fw-semibold">Approved</span>
        }
        else if (Model.IsApproved == State.NotApproved)
        {
            <span class="badge bg-danger rounded-3 fw-semibold">Not Approved</span>
        }
        else if (Model.IsApproved == State.Waiting)
        {
            <span class="badge bg-warning rounded-3 fw-semibold">Waiting</span>
        }
        <hr />
        <br/>
        <h4 class="mb-2">Patient Details:</h4>
        <p class="mb-1"><b>Patient Name:</b>@Model.Patient.FullName</p>
        <p class="mb-1"><b>Patient Email:</b>@Model.Patient.Email</p>
        <p class="mb-1"><b>Patient Phone:</b>@Model.Patient.Phone</p>
        <p class="mb-1"><b>Patient Age:</b>@Model.Patient.Age</p>
        <br />
        <h4>Note:</h4>
        <form method="post" asp-controller="Doctor" asp-action="AppointmentDetails">
            <input type="hidden" name="id" value="@Model.AppointmentId" />
            <textarea name="note" style="width:100%;min-height:200px;">@Model.Note</textarea>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
        
    </div>
</div>

DoctorAppointmentSystem.WebUI/Views/Doctor/Index.cshtml
@model Doctor
@{
    Layout = "_DoctorLayout";
}

<div style="background-color:var(--bs-info-bg-subtle)" class="card">
    <div class="card-body">
        <h5 class="mb-3">Welcome!</h5>
        <h3 class="mb-3">@Model.FullName</h3>
        <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere mollitia fuga iste praesentium alias optio, sapiente minus magni quos doloremque laboriosam voluptatem molestiae dicta commodi aspernatur quo dolorum saepe at!</p>
        <form class="form-inline home-searchbar d-flex w-50">
            <input style="background-color: white;" class="form-control mr-sm-2 me-2" type="search" placeholder="Search Doctor" aria-label="Search">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 d-flex align-items-stretch">
        <div class="card w-100 alert alert-secondary">
            <div class="card-body p-4">
                <h5 class="card-title fw-semibold mb-4">Today's Bookings</h5>
                <div class="table-responsive">
                    <table class="table text-nowrap mb-0 align-middle table-hover table-striped">
                        <thead class="text-dark fs-4">
                            <tr>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">#</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Patient</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Phone</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Email</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Age</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Scheduled Date & Time</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Approval Status</h6>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var appointment in Model.Appointments)
                            {
                                if (appointment.DateTime == DateTime.Now)
                                {
                                    <tr>
                                        <td class="border-bottom-0"><h6 class="fw-semibold mb-0">@appointment.AppointmentId</h6></td>
                                        <td class="border-bottom-0">
                                            <a class="d-flex align-items-center" asp-controller="Doctor" asp-action="PatientProfile" asp-route-id="@appointment.Patient.PatientId">
                                                <h6 class="fw-semibold mb-1 mx-2">@appointment.Patient.FullName</h6>
                                                <button style="padding:4px" class="btn btn-outline-secondary btn-sm">></button>
                                            </a>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-1">@appointment.Patient.Phone</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-1">@appointment.Patient.Email</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-1">@appointment.Patient.Age</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <p class="mb-0 fw-normal">@appointment.DateTime.ToLongDateString()-@appointment.DateTime.ToShortTimeString()</p>
                                        </td>
                                        <td class="border-bottom-0">
                                            @if (appointment.IsApproved == State.Approved)
                                            {
                                                <span class="badge bg-success rounded-3 fw-semibold">Approved</span>
                                            }
                                            else if (appointment.IsApproved == State.NotApproved)
                                            {
                                                <span class="badge bg-danger rounded-3 fw-semibold">Not Approved</span>
                                            }
                                            else if (appointment.IsApproved == State.Waiting)
                                            {
                                                <span class="badge bg-warning rounded-3 fw-semibold">Waiting</span>
                                            }
                                        </td>
                                        <td>
                                            <a class="btn btn-secondary btn-sm" asp-controller="Doctor" asp-action="AppointmentDetails" asp-route-id="@appointment.AppointmentId">Details</a>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12 d-flex align-items-stretch">
        <div style="margin-bottom:0px;" class="card w-100 alert alert-secondary">
            <div class="card-body p-4">
                <h5 class="card-title fw-semibold mb-4">Your Upcoming Bookings</h5>
                <div class="table-responsive">
                    <table class="table text-nowrap mb-0 align-middle table-hover table-striped">
                        <thead class="text-dark fs-4">
                            <tr>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">#</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Patient</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Phone</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Email</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Age</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Scheduled Date & Time</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Approval Status</h6>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var appointment in Model.Appointments)
                            {
                                if (appointment.DateTime >= DateTime.Now)
                                {
                                    <tr>
                                        <td class="border-bottom-0"><h6 class="fw-semibold mb-0">@appointment.AppointmentId</h6></td>
                                        <td class="border-bottom-0">
                                            <a class="d-flex align-items-center" asp-controller="Doctor" asp-action="PatientProfile" asp-route-id="@appointment.Patient.PatientId">
                                                <h6 class="fw-semibold mb-1 mx-2">@appointment.Patient.FullName</h6>
                                                <button style="padding:4px" class="btn btn-outline-secondary btn-sm">></button>
                                            </a>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-1">@appointment.Patient.Phone</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-1">@appointment.Patient.Email</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <h6 class="fw-semibold mb-1">@appointment.Patient.Age</h6>
                                        </td>
                                        <td class="border-bottom-0">
                                            <p class="mb-0 fw-normal">@appointment.DateTime.ToLongDateString()-@appointment.DateTime.ToShortTimeString()</p>
                                        </td>
                                        <td class="border-bottom-0">
                                            @if (appointment.IsApproved == State.Approved)
                                            {
                                                <span class="badge bg-success rounded-3 fw-semibold">Approved</span>
                                            }
                                            else if (appointment.IsApproved == State.NotApproved)
                                            {
                                                <span class="badge bg-danger rounded-3 fw-semibold">Not Approved</span>
                                            }
                                            else if (appointment.IsApproved == State.Waiting)
                                            {
                                                <span class="badge bg-warning rounded-3 fw-semibold">Waiting</span>
                                            }
                                        </td>
                                        <td>
                                            <a class="btn btn-secondary btn-sm" asp-controller="Doctor" asp-action="AppointmentDetails" asp-route-id="@appointment.AppointmentId">Details</a>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12" style="padding: 0px 12px">
        <a asp-controller="Doctor" asp-action="AppointmentList" class="btn btn-primary w-100">Show All Appointments</a>
    </div>

</div>

DoctorAppointmentSystem.WebUI/Views/Doctor/LeaveRequest.cshtml
@model DayOff
@{
    Layout = "_DoctorLayout";
}

<div class="card alert alert-secondary">
    <div class="card-body">
        <h5 class="card-title fw-semibold mb-4">Requesting Permission</h5>
        <form method="post" asp-controller="Doctor" asp-action="LeaveRequest">
            <div class="row g-2">
                <div class="col-md">
                    <div class="form-floating mb-3">
                        <input asp-for="@Model.StartDate" type="date" class="form-control bg-white" id="floatingInput" placeholder="Date">
                        <label for="floatingInput">Start Date</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating mb-3">
                        <input asp-for="@Model.EndDate" type="date" class="form-control bg-white" id="floatingInput" placeholder="Date">
                        <label for="floatingInput">End Date</label>
                    </div>
                </div>
            </div>
            <div class="form-floating mb-3">
              <textarea asp-for="@Model.Reason" class="form-control" placeholder="Reason" id="floatingTextarea2" style="height: 200px;background:white;"></textarea>
                <label for="floatingTextarea2">Reason for Leave</label>
            </div>
            <button class="btn btn-primary w-100" type="submit">Take a Permission</button>
        </form>
    </div>
</div>

DoctorAppointmentSystem.WebUI/Views/Doctor/OffDays.cshtml
@model List<DayOff>
@{
    Layout = "_DoctorLayout";
}

<div class="card alert alert-secondary">
    <div class="card-body">
        <h5 class="card-title fw-semibold mb-4">Off Days</h5>
        @foreach(var item in Model)
        {
            if(item.EndDate > DateTime.Now)
            {
                <div class="card mt-3 p-0">
                    <div class="card-header d-flex align-items-center justify-content-between" data-bs-toggle="collapse" href="#Collapse@(item.Id.ToString())" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">
                        @if (item.IsApproved == State.Approved)
                        {
                            <span class="badge bg-success rounded-3 fw-semibold">Approved</span>
                        }
                        else if (item.IsApproved == State.NotApproved)
                        {
                            <span class="badge bg-danger rounded-3 fw-semibold">Not Approved</span>
                        }
                        else if (item.IsApproved == State.Waiting)
                        {
                            <span class="badge bg-warning rounded-3 fw-semibold">Waiting</span>
                        }
                        <span>
                            <b>Date:</b> @item.StartDate.ToShortDateString() - @item.EndDate.ToShortDateString()
                        </span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-caret-down"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M6 10l6 6l6 -6h-12" /></svg>
                    </div>
                    <div style="padding:20px" class="card-body collapse multi-collapse " id="Collapse@(item.Id.ToString())">
                        <label class="fw-larger p-1"><b>Reason:</b></label>
                        <textarea style="border: none;width: 100%;height:100px;margin-top:15px" class="p-3 mb-2" disabled>@item.Reason</textarea>
                        <form method="post" asp-controller="Doctor" asp-action="OffDays">
                            <input type="hidden" name="id" value="@item.Id" />
                            <button class="btn btn-danger btn-sm w-100" type="submit">Cancel the Permission</button>
                        </form>
                    </div>
                </div>
            }
        }
    </div>
</div>

DoctorAppointmentSystem.WebUI/Views/Doctor/PastAppointmentList.cshtml
@model List<Appointment>
@{
    Layout = "_DoctorLayout";
}

<div class="card alert alert-secondary">
    <div class="card-body">
        <h5 class="card-title fw-semibold mb-4">Past Appointments</h5>
        <div class="homepage-bookings">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Patient</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Age</th>
                        <th scope="col">Scheduled Date & Time</th>
                        <th scope="col">IsApproved</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var appointment in Model)
                    {
                        if (appointment.DateTime < DateTime.Now)
                        {
                            <tr>
                                <th scope="row">@appointment.AppointmentId</th>
                                <td>
                                    <a class="d-flex align-items-center" asp-controller="Doctor" asp-action="PatientProfile" asp-route-id="@appointment.Patient.PatientId">
                                        <h6 class="fw-semibold mb-1 mx-2">@appointment.Patient.FullName</h6>
                                        <button style="padding:4px" class="btn btn-outline-secondary btn-sm">></button>
                                    </a>
                                </td>
                                <td>@appointment.Patient.Phone</td>
                                <td>@appointment.Patient.Age</td>
                                <td>@appointment.DateTime.ToLongDateString()-@appointment.DateTime.ToShortTimeString()</td>
                                <td>
                                    @if (appointment.IsApproved == State.Approved)
                                    {
                                        <span class="badge bg-success rounded-3 fw-semibold">Approved</span>
                                    }
                                    else if (appointment.IsApproved == State.NotApproved)
                                    {
                                        <span class="badge bg-danger rounded-3 fw-semibold">Not Approved</span>
                                    }
                                    else if (appointment.IsApproved == State.Waiting)
                                    {
                                        <span class="badge bg-warning rounded-3 fw-semibold">Waiting</span>
                                    }
                                </td>
                                <td>
                                    <a class="btn btn-secondary btn-sm" asp-controller="Doctor" asp-action="AppointmentDetails" asp-route-id="@appointment.AppointmentId">Details</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

DoctorAppointmentSystem.WebUI/Views/Doctor/Schedule.cshtml
@model List<Schedule>
@{
    Layout = "_DoctorLayout";

}

<div class="card">
    <div class="card-body">
        <h5 class="card-title fw-semibold mb-4">My Schedule</h5>
        <form method="post" asp-controller="Doctor" asp-action="Schedule">
            <ul class="list-group mb-2">

                @for (int i = 0; i < Model.Count; i++)
                {
                    <li class="list-group-item">
                        <input asp-for="@Model[i].DoctorId" type="hidden" />
                        <input asp-for="@Model[i].ScheduleId" type="hidden" />
                        <input asp-for="@Model[i].StartTime" type="hidden" />
                        <input asp-for="@Model[i].EndTime" type="hidden" />
                        <input asp-for="@Model[i].Interval" type="hidden" />
                        <input asp-for="@Model[i].DayOfWeek" type="hidden" />
                        <input asp-for="@Model[i].IsWorkingDay" id="@(Model[i].ScheduleId)" class="form-check-input me-1" type="checkbox" value="@Model[i].IsWorkingDay.ToString()" checked="@Model[i].IsWorkingDay" />
                        <div class="ms-2 me-auto d-inline-block">
                            <div class="fw-bold">@Model[i].DayOfWeek</div>
                            @Model[i].StartTime.ToString("hh\\:mm") - @Model[i].EndTime.ToString("hh\\:mm")
                        </div>
                    </li>
                }
            </ul>
          <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>

<script>
    let boxes = document.querySelectorAll(".form-check-input");
    boxes.forEach((item) => {
        item.addEventListener('click', () => {
            if (item.value == "False") {
                item.value = "True";
            } 
            else {
                item.value = "False";
            }
        });
    });
</script>